/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;

/**
 *
 * @author LOGANATHAN
 */
public class manage extends javax.swing.JFrame {

    /**
     * Creates new form manage
     */
    public manage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        REGISTERBTN = new javax.swing.JButton();
        REGISTERBTN3 = new javax.swing.JButton();
        REGISTERBTN4 = new javax.swing.JButton();
        REGISTERBTN5 = new javax.swing.JButton();
        REGISTERBTN6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));

        REGISTERBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN.setText("CREATE AN EVENT");
        REGISTERBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTNActionPerformed(evt);
            }
        });

        REGISTERBTN3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN3.setText("BOOKING HISTORY");
        REGISTERBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN3ActionPerformed(evt);
            }
        });

        REGISTERBTN4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN4.setText("LOGOUT");
        REGISTERBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN4ActionPerformed(evt);
            }
        });

        REGISTERBTN5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN5.setText("VIEW VENUES");
        REGISTERBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN5ActionPerformed(evt);
            }
        });

        REGISTERBTN6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN6.setText("BOOK AN EVENT");
        REGISTERBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(REGISTERBTN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REGISTERBTN5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REGISTERBTN4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REGISTERBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REGISTERBTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(REGISTERBTN)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN6)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN3)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN5)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN4)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTERBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTNActionPerformed
       
        
          
        this.setVisible(false);
        new CREATE().setVisible(true);
        

    }//GEN-LAST:event_REGISTERBTNActionPerformed

    private void REGISTERBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN3ActionPerformed
        // TODO add your handling code here:
        
         this.setVisible(false);
        new Bookinghistory().setVisible(true);
    }//GEN-LAST:event_REGISTERBTN3ActionPerformed

    private void REGISTERBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_REGISTERBTN4ActionPerformed

    private void REGISTERBTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN5ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new VENUES().setVisible(true);
    }//GEN-LAST:event_REGISTERBTN5ActionPerformed

    private void REGISTERBTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN6ActionPerformed
        // TODO add your handling code here:
        
        
          
        this.setVisible(false);
        new Book().setVisible(true);
        
    }//GEN-LAST:event_REGISTERBTN6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGISTERBTN;
    private javax.swing.JButton REGISTERBTN3;
    private javax.swing.JButton REGISTERBTN4;
    private javax.swing.JButton REGISTERBTN5;
    private javax.swing.JButton REGISTERBTN6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
