/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;

/**
 *
 * @author LOGANATHAN
 */
public class VENUES extends javax.swing.JFrame {

    /**
     * Creates new form VENUES
     */
    public VENUES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        REGISTERBTN5 = new javax.swing.JButton();
        REGISTERBTN6 = new javax.swing.JButton();
        REGISTERBTN7 = new javax.swing.JButton();
        REGISTERBTN8 = new javax.swing.JButton();
        REGISTERBTN9 = new javax.swing.JButton();
        REGISTERBTN10 = new javax.swing.JButton();
        REGISTERBTN11 = new javax.swing.JButton();
        REGISTERBTN12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("VENUES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        REGISTERBTN5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN5.setText("Go Back");
        REGISTERBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN5ActionPerformed(evt);
            }
        });

        REGISTERBTN6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN6.setText("ANNA AUDITORIUM - VIT (VELLORE) - 10000");
        REGISTERBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN6ActionPerformed(evt);
            }
        });

        REGISTERBTN7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN7.setText("GRD - CHENNAI - 10000");
        REGISTERBTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN7ActionPerformed(evt);
            }
        });

        REGISTERBTN8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN8.setText("BLUE ROOM (WOOD ROSE) - BANGALORE - 20000");
        REGISTERBTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN8ActionPerformed(evt);
            }
        });

        REGISTERBTN9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN9.setText("RD's Fiesta - DELHI - 30000");
        REGISTERBTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN9ActionPerformed(evt);
            }
        });

        REGISTERBTN10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN10.setText("SWAMI KRUPA HALL - PUNE - 35000");
        REGISTERBTN10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN10ActionPerformed(evt);
            }
        });

        REGISTERBTN11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN11.setText("NEW CASTLE AUDITORIUM - KERELA - 50000");
        REGISTERBTN11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN11ActionPerformed(evt);
            }
        });

        REGISTERBTN12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REGISTERBTN12.setText("SAI PLAZA HALL - MUMBAI - 45000");
        REGISTERBTN12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERBTN12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(REGISTERBTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(REGISTERBTN12, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTERBTN11, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTERBTN10, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTERBTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTERBTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTERBTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGISTERBTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(REGISTERBTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(REGISTERBTN12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(REGISTERBTN5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTERBTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN5ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        new manage().setVisible(true);
    }//GEN-LAST:event_REGISTERBTN5ActionPerformed

    private void REGISTERBTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN6ActionPerformed

    private void REGISTERBTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN7ActionPerformed

    private void REGISTERBTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN8ActionPerformed

    private void REGISTERBTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN9ActionPerformed

    private void REGISTERBTN10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN10ActionPerformed

    private void REGISTERBTN11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN11ActionPerformed

    private void REGISTERBTN12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERBTN12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTERBTN12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENUES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENUES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENUES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENUES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENUES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGISTERBTN10;
    private javax.swing.JButton REGISTERBTN11;
    private javax.swing.JButton REGISTERBTN12;
    private javax.swing.JButton REGISTERBTN5;
    private javax.swing.JButton REGISTERBTN6;
    private javax.swing.JButton REGISTERBTN7;
    private javax.swing.JButton REGISTERBTN8;
    private javax.swing.JButton REGISTERBTN9;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
